In [1]:
import numpy as np

In [3]:
a = np.array([[64392,31655],[32579,0],[49248,462],[0,0]])
print(a)

[[64392 31655]
 [32579     0]
 [49248   462]
 [    0     0]]


In [4]:
print('Printing numpy array attributes')

Printing numpy array attributes


In [5]:
print('Array shape is :',a.shape)

Array shape is : (4, 2)


In [6]:
print('Array dimensions are :',a.ndim)

Array dimensions are : 2


In [7]:
print('Length of each elements in array in bytes is :',a.itemsize)

Length of each elements in array in bytes is : 4


## Exercise 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [12]:
b = np.arange(110,201,10).reshape(5,2)
b

array([[110, 120],
       [130, 140],
       [150, 160],
       [170, 180],
       [190, 200]])

## Exercise 3: Following is the provided numPy array. Return array of items by taking the third column from all rows

In [15]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [30]:
c = sampleArray[:,2:]
c

array([[33],
       [66],
       [99]])

In [32]:
# Find middle column
c = sampleArray[:,1:2]
c

array([[22],
       [55],
       [88]])

In [33]:
# First 2 rows
sampleArray[:2]

array([[11, 22, 33],
       [44, 55, 66]])

In [34]:
# first 2 rows and 2 columns
sampleArray[:2,:2]

array([[11, 22],
       [44, 55]])

## Exercise 4: Return array of odd rows and even columns from below numpy array

In [36]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [37]:
sampleArray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [38]:
sampleArray[0::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

## Exercise 5: Create a result array by adding the following two NumPy arrays. 

In [41]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

In [42]:
a = arrayOne + arrayTwo

In [43]:
a

array([[20, 39, 33],
       [25, 25, 28]])

## Exercise 6: Split the array into four equal-sized sub-arrays
Note: Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

In [55]:
b = np.arange(10,34,1).reshape((8*3))

In [56]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33])

In [57]:
b.reshape(6*4)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33])