In [1]:
import numpy as np

### 17. Write a NumPy program to check whether each element of a given array is composed of digits only, lower case letters only and upper case letters only. 

In [2]:
x = np.array(['Python','PHP','js','html5','CSs'])

In [3]:
r1 = np.char.isdigit(x)
r2 = np.char.islower(x)
r3 = np.char.isupper(x)

In [4]:
print('Is digit is :',r1)

Is digit is : [False False False False False]


In [6]:
print('Lower case only :',r2)

Lower case only : [False False  True  True False]


In [7]:
print('Upper case only : ',r3)

Upper case only :  [False  True False False False]


#### 18. Write a NumPy program to check whether each element of a given array starts with "P". 

In [8]:
x

array(['Python', 'PHP', 'js', 'html5', 'CSs'], dtype='<U6')

In [10]:
np.char.startswith(x,'P')

array([ True,  True, False, False, False])

#### 19. Write a NumPy program to add two zeros to the beginning of each element of a given array of string values. 

In [11]:
a = np.random.random((1,6))

In [12]:
a

array([[0.6626599 , 0.37641519, 0.69234132, 0.14210769, 0.00983934,
        0.09091692]])

In [14]:
a = np.array(['1.1','2.2','3.3','4.4','5.5'])
a

array(['1.1', '2.2', '3.3', '4.4', '5.5'], dtype='<U3')

In [16]:
np.char.add('00',a)

array(['001.1', '002.2', '003.3', '004.4', '005.5'], dtype='<U5')

#### 20. Write a NumPy program to replace a specific character with another in a given array of string values.

In [17]:
b = np.array(['Python-numpy','python-pandas','python-seaborn'])

In [19]:
c = np.char.strip(np.char.replace(b,'-','='))

In [20]:
c

array(['Python=numpy', 'python=pandas', 'python=seaborn'], dtype='<U14')

#### 21. Write a NumPy program to count a given word in each row of a given array of string values. 

In [21]:
g = np.array([['python','css','html'],['python','python','js'],['css','php','python']])

In [22]:
np.char.count(g,'python')

array([[1, 0, 0],
       [1, 1, 0],
       [0, 0, 1]])

#### 22. Write a NumPy program to split a given text into lines and split the single line into array values.

In [23]:
w = """
01 A President
02 B Prime Minister
03 C Finance Minister
04 D Health Minister
05 E Defence Minister
06 F Home Minister
"""

In [24]:
w

'\n01 A President\n02 B Prime Minister\n03 C Finance Minister\n04 D Health Minister\n05 E Defence Minister\n06 F Home Minister\n'

In [25]:
text_lines = w.splitlines()

In [26]:
text_lines = [r.split('\t') for r in text_lines]

In [27]:
result =np.array(text_lines,dtype = np.str)

C:\Users\sai\AppData\Local\Temp\ipykernel_5236\3138150597.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  result =np.array(text_lines,dtype = np.str)


In [28]:
result

array([[''],
       ['01 A President'],
       ['02 B Prime Minister'],
       ['03 C Finance Minister'],
       ['04 D Health Minister'],
       ['05 E Defence Minister'],
       ['06 F Home Minister']], dtype='<U21')