In [1]:
import numpy as np

### 1. Get the maximum value from given matrix

In [4]:
a = np.matrix('[64,1;12,3]')
a

matrix([[64,  1],
        [12,  3]])

In [5]:
np.max(a)

64

### 2. Get the minimum value from given matrix

In [6]:
np.min(a)

1

### 3. Find the number of rows and columns of a given matrix using NumPy

In [7]:
a.size

4

In [9]:
a.shape

(2, 2)

### 4. Select the elements from a given matrix

In [10]:
b = np.matrix('[1,2,3,;4,5,6]')
b

matrix([[1, 2, 3],
        [4, 5, 6]])

In [11]:
b.take(5)
# Give index 

matrix([[6]])

In [16]:
b[1:,2:]

matrix([[6]])

### 5. Find the sum of values in a matrix

In [17]:
np.sum(a)

80

### 6. Calculate the sum of the diagonal elements of a NumPy array

In [18]:
np.trace(a)

67

###  7.Adding and Subtracting Matrices in Python

In [19]:
a = np.array([[10,20],[30,40]])
b = np.array([[100,200],[300,400]])
display(a,b)

array([[10, 20],
       [30, 40]])

array([[100, 200],
       [300, 400]])

In [20]:
a + b

array([[110, 220],
       [330, 440]])

In [21]:
a - b

array([[ -90, -180],
       [-270, -360]])

In [22]:
np.add(a,b)

array([[110, 220],
       [330, 440]])

In [23]:
np.subtract(a,b)

array([[ -90, -180],
       [-270, -360]])

###  8. Ways to add row/columns in numpy array

##### Method 1 using append

In [24]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.append(a,[10,11,12])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
b = np.array([[10],[11],[12]])
b

array([[10],
       [11],
       [12]])

In [34]:
np.concatenate([a,b],axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [37]:
c = np.array([[100],[101],[102]])
c

array([[100],
       [101],
       [102]])

In [41]:
np.insert(a,0,c,axis=1)

array([[100, 101, 102,   1,   2,   3],
       [100, 101, 102,   4,   5,   6],
       [100, 101, 102,   7,   8,   9]])

In [46]:
np.insert(a,0,c,axis=0)

array([[100, 100, 100],
       [101, 101, 101],
       [102, 102, 102],
       [  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

### 9 Matrix Multiplication in NumPy

In [47]:
p = np.array([[5,15],[25,35]])
q = np.array([[10,20],[30,40]])

In [51]:
np.dot(p,q)

array([[ 500,  700],
       [1300, 1900]])

In [48]:
p * q

array([[  50,  300],
       [ 750, 1400]])

In [50]:
np.dot(q,p)

array([[ 550,  850],
       [1150, 1850]])

### 10. How to inverse a matrix using NumPy

In [52]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.linalg.inv(a)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

###  Count the nique

In [54]:
np.unique(a,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

### 11. Multiply matrices of complex numbers using NumPy in Python

In [55]:
x = np.array([2+3j, 4+5j])
y = np.array([8+7j, 5+6j])

In [56]:
np.vdot(x,y)

(87-11j)

### 12. Compute the outer product of two given vectors using NumPy in Python

In [57]:
a1 = np.array([1,2])
a2 = np.array([10,25])
display(a1,a2)

array([1, 2])

array([10, 25])

In [58]:
np.outer(a1,a2)

array([[10, 25],
       [20, 50]])

### 13. Calculate inner, outer, and cross products of matrices and vectors using NumPy

In [59]:
np.inner(a1,a2)

60

In [60]:
np.outer(a1,a2)

array([[10, 25],
       [20, 50]])

In [61]:
np.cross(a1,a2)

array(5)

### 14. Compute the covariance matrix of two given NumPy arrays

In [62]:
np.cov(a1,a2)

array([[  0.5,   7.5],
       [  7.5, 112.5]])

In [63]:
# krenon product
np.kron(a1,a2)

array([10, 25, 20, 50])

### Python | Numpy matrix.tolist()

In [64]:
c = np.matrix('[1,2,3;4,5,6]')
c

matrix([[1, 2, 3],
        [4, 5, 6]])

In [65]:
c.tolist()

[[1, 2, 3], [4, 5, 6]]

# Numpy Indexing

### 1. Replace NumPy array elements that doesn’t satisfy the given condition

In [66]:
a = np.array([10,20,30,40,5])
a

array([10, 20, 30, 40,  5])

In [67]:
a[a>10]

array([20, 30, 40])

In [68]:
a [a>10] = 0

In [69]:
a

array([10,  0,  0,  0,  5])

In [70]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
b[b>5] = -1

In [72]:
b

array([[ 1,  2,  3],
       [ 4,  5, -1],
       [-1, -1, -1]])

### 2. Return the indices of elements where the given condition is satisfied

In [73]:
c = np.arange(1,10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
c1 = np.where(c<4)

In [77]:
c[c1]

array([1, 2, 3])

In [78]:
c2 = np.where(c>4)

In [79]:
c[c2]

array([5, 6, 7, 8, 9])

### 3. Replace NaN values with average of columns

In [80]:
a = np.array([[1,2,3,np.nan],[5,6,np.nan,np.nan],[9,np.nan,np.nan,12]])
a

array([[ 1.,  2.,  3., nan],
       [ 5.,  6., nan, nan],
       [ 9., nan, nan, 12.]])

In [82]:
col_mean = np.nanmean(a,axis=1)
col_mean

array([ 2. ,  5.5, 10.5])

In [83]:
b= np.where(np.isnan(a))

In [86]:
a[b] = np.take(col_mean,b[1])

IndexError: index 3 is out of bounds for axis 0 with size 3

###  4.Python | Replace negative value with zero in numpy array

In [88]:
a = np.array([1,2,3,10,-1,-5,-8,8,9,10])
a

array([ 1,  2,  3, 10, -1, -5, -8,  8,  9, 10])

In [89]:
a[a<0] = 0

In [90]:
a

array([ 1,  2,  3, 10,  0,  0,  0,  8,  9, 10])

### 5. How to get values of an NumPy array at certain index positions?

In [91]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [92]:
a2 = np.array([10,20,30])
a2

array([10, 20, 30])

In [93]:
# change 1st and 5th value in a1 as 10 and 20
a1.put([0,4],a2)

In [94]:
a1

array([10,  2,  3,  4, 20])

### 6. Find indices of elements equal to zero in a NumPy array

In [95]:
a =  np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8])
a

array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8])

In [98]:
res = np.where(a == 0)[0]

In [99]:
res
# index position of zeros in array

array([ 1,  3,  5,  6, 11], dtype=int64)

### 7. How to Remove columns in Numpy array that contains non-numeric values?

In [2]:
a = np.array([[10.5, 22.5, np.nan],[41, 52.5, np.nan]])
a

array([[10.5, 22.5,  nan],
       [41. , 52.5,  nan]])

In [3]:
a[:,~np.isnan(a).any(axis=0)]

array([[10.5, 22.5],
       [41. , 52.5]])

### 8. How to access different rows of a multidimensional NumPy array?

In [4]:
a = np.arange(10,100,10).reshape(3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [5]:
a[1]

array([40, 50, 60])

In [6]:
a[:2]

array([[10, 20, 30],
       [40, 50, 60]])

### 9. Get row numbers of NumPy array having element larger than X

In [7]:
b = np.array([[1, 2, 3, 4, 5],
                  [10, -3, 30, 4, 5],
                  [3, 2, 5, -4, 5],
                  [9, 7, 3, 6, 5] 
                 ])
b

array([[ 1,  2,  3,  4,  5],
       [10, -3, 30,  4,  5],
       [ 3,  2,  5, -4,  5],
       [ 9,  7,  3,  6,  5]])

In [8]:
x = 6

In [10]:
np.where(np.any(b > x,axis =0))

(array([0, 1, 2], dtype=int64),)

In [11]:
np.where(np.any(b > x,axis =1))

(array([1, 3], dtype=int64),)

### 10. Get filled the diagonals of NumPy array

In [14]:
a = np.zeros((4,4))

In [15]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.fill_diagonal(a,val=1)

In [18]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
b = np.identity(3)

In [20]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.fill_diagonal(b,val=-1)

In [27]:
b

array([[-1.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 0.,  0., -1.]])

In [28]:
c = np.full((4,4),fill_value=True)
c

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
np.fill_diagonal(c,val=False)

In [30]:
c

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

### 11. Check elements present in the NumPy array

In [32]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [33]:
b = np.array([1,3,5])
b

array([1, 3, 5])

In [34]:
c = np.isin(a,b)

In [35]:
c

array([ True,  True,  True, False, False])

### 12. Combined array index by index

In [36]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
display(a1,a2)  

array([1, 2, 3])

array([4, 5, 6])

In [39]:
np.dstack((a1,a2))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# Numpy - Random

### 1. Create a Numpy array with random values

In [40]:
a = np.empty(2)
a

array([1.10512558e-311, 1.10513573e-311])

In [41]:
b = np.empty((2,2))
b

array([[1., 1.],
       [1., 1.]])

### 2. How to choose elements from the list with different probability using NumPy?

In [42]:
list1 = [10,20,30,40,50]

In [43]:
a = np.random.choice(list1)

In [44]:
a

40

### 3. How to get weighted random choice in Python?