In [1]:
import numpy as np

### 1. Write a NumPy program to print the NumPy version in your system.

In [2]:
np.__version__

'1.21.5'

### 2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [3]:
a = np.array([12.23,13.32,100,36.32])
a

array([ 12.23,  13.32, 100.  ,  36.32])

### 3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [8]:
a = np.arange(2,11).reshape(3,3)

In [9]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [10]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
a[6] = 11
# updating sixth

In [12]:
a

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

### 5. Write a NumPy program to create an array with values ranging from 12 to 38.

In [13]:
a = np.arange(12,38)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

### 6. Write a NumPy program to reverse an array (first element becomes last). 

In [14]:
a[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

### 7. Write a NumPy program to convert an array to a float type.

In [15]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [20]:
b = a.astype(float)

In [18]:
type(a)

numpy.ndarray

In [19]:
a.dtype

dtype('int32')

In [21]:
b.dtype

dtype('float64')

### 8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [22]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
a[1:-1,1:-1] = 0

In [24]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 9. Write a NumPy program to add a border (filled with 0's) around an existing array

In [25]:
x = np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# adding border values to 0
x = np.pad(x,pad_width=1,mode='constant',constant_values=0)
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

### 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [27]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
x = np.ones((8,8),dtype=int)
x

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [33]:
x[::2,1::2] = 0

In [34]:
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [35]:
x[1::2,::2]=0
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 11. Write a NumPy program to convert a list and tuple into arrays.

In [36]:
a = [1,2,3,4,5,6,7,8,9]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
a1 = np.array(a)

In [38]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
b = ([1,2,3],[4,5,6])
b

([1, 2, 3], [4, 5, 6])

In [40]:
b1 = np.array(b)
b1

array([[1, 2, 3],
       [4, 5, 6]])

### 12. Write a NumPy program to append values to the end of an array.

In [42]:
x = np.array([10,20,30])
x

array([10, 20, 30])

In [45]:
x = np.append(x,[40])
x

array([10, 20, 30, 40])

In [46]:
x = np.append(x,[[50,60],[70,80]])
x

array([10, 20, 30, 40, 50, 60, 70, 80])

### 13. Write a NumPy program to create an empty and a full array.

In [47]:
x = np.empty((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
c = np.empty((3,4))
c

array([[1.32185616e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 6.82116729e-043, 5.89211070e-091,
        8.60677435e-067],
       [6.58891631e-043, 6.23869653e+174, 3.99910963e+252,
        9.12885439e+169]])

In [49]:
a = np.full((3,5),6)
a

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### 14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees and vice versa. Values are stored into a NumPy array. 

In [50]:
f_values = [0, 12, 45.21, 34, 99.91, 32]
f_values

[0, 12, 45.21, 34, 99.91, 32]

In [52]:
a = np.array(f_values)
a

array([ 0.  , 12.  , 45.21, 34.  , 99.91, 32.  ])

In [55]:
b = np.round((5 * a/9-5*32/9),2)
b

array([-17.78, -11.11,   7.34,   1.11,  37.73,   0.  ])

### 15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers. 

In [57]:
x = np.sqrt([1+5j])
y = np.sqrt([10j+89])
display(x,y)

array([1.74628456+1.4316109j])

array([9.44881039+0.52916714j])

In [58]:
x.real

array([1.74628456])

In [59]:
y.real

array([9.44881039])

In [60]:
x.imag

array([1.4316109])

In [61]:
y.imag

array([0.52916714])

### 16. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [62]:
x = np.array([10,20,30],dtype=float)
x

array([10., 20., 30.])

In [63]:
print('Size of the arrray is :',x.size)

Size of the arrray is : 3


In [65]:
print('Array element size in bytes is:',x.itemsize)

Array element size in bytes is: 8


In [67]:
print('Total ayyay sixe is:',x.nbytes)

Total ayyay sixe is: 24


### 17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [68]:
a1 = np.array([2,4,6,8,10])
a2 = np.array([6,10])

In [69]:
np.in1d(a1,a2)

array([False, False,  True, False,  True])

### 18. Write a NumPy program to find common values between two arrays. 

In [70]:
print('Common values are :')
np.intersect1d(a1,a2)

Common values are :


array([ 6, 10])

### 19. Write a NumPy program to get the unique elements of an array. 

In [71]:
x = np.array([10,10,10,50,50,100,120,120])
x

array([ 10,  10,  10,  50,  50, 100, 120, 120])

In [72]:
np.unique(x)

array([ 10,  50, 100, 120])

### 20. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.### 

In [73]:
a1 = np.array([0, 10, 20, 40, 60, 80])
a2 = np.array([10, 30, 40, 50, 70])

In [74]:
np.setdiff1d(a1,a2)

array([ 0, 20, 60, 80])

### 21. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays. 

### 22. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

In [75]:
np.union1d(a1,a2)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

### 23. Write a NumPy program to test whether all elements in an array evaluate to True

### 24. Write a NumPy program to test whether any array element along a given axis evaluates to True.

### 25. Write a NumPy program to construct an array by repeating.

In [76]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [77]:
x = np.tile(a,2)

In [78]:
x

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [79]:
np.tile(a,3)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

### 26. Write a NumPy program to repeat elements of an array.

In [80]:
# repeat no 3 by 4 times
np.repeat(3,4)

array([3, 3, 3, 3])

In [81]:
a = [[1,2],[3,4]]
a

[[1, 2], [3, 4]]

In [82]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

### 27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

In [83]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [84]:
np.min(x)

1

In [85]:
np.max(x)

5

In [86]:
np.argmax(x)
# gives highest index position

4

In [87]:
# gives lowest index position
np.argmin(x)

0

### 28. Write a NumPy program compare two given arrays.

In [88]:
a = np.array([1,2])
b = np.array([3,4])

In [89]:
a > b

array([False, False])

In [90]:
np.greater(a,b)

array([False, False])

In [91]:
a >= b

array([False, False])

In [92]:
np.greater_equal(a,b)

array([False, False])

In [93]:
a < b

array([ True,  True])

In [94]:
np.less(a,b)

array([ True,  True])

In [95]:
a <= b

array([ True,  True])

In [96]:
np.less_equal(a,b)

array([ True,  True])

### 29. Write a NumPy program to sort an along the first, last axis of an array.

In [98]:
a = np.array([[4,6],[2,1]])
a

array([[4, 6],
       [2, 1]])

In [99]:
np.sort(a,axis =0)

array([[2, 1],
       [4, 6]])

In [100]:
np.sort(a,axis=1)

array([[4, 6],
       [1, 2]])

### 30. Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name). 

### 31. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [101]:
x = np.array([[0,5,10,20,30],[10,5,15,20]])
x

C:\Users\sai\AppData\Local\Temp\ipykernel_300\3170393250.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([[0,5,10,20,30],[10,5,15,20]])


array([list([0, 5, 10, 20, 30]), list([10, 5, 15, 20])], dtype=object)

In [102]:
x = np.array([[0, 10, 20], [20, 30, 40]])
x

array([[ 0, 10, 20],
       [20, 30, 40]])

In [103]:
x[x>10]

array([20, 20, 30, 40])

In [104]:
# their indices
np.nonzero(x>10)

(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))

### 32. Write a NumPy program to save a NumPy array to a text file.

### 33. Write a NumPy program to find the memory size of a NumPy array. 

In [105]:
s = np.zeros((4,4))
s

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
s.itemsize

8

In [107]:
(s.size)

16

In [108]:
s.size * s.itemsize

128

### 34. Write a NumPy program to create an array of ones and an array of zeros. 

In [109]:
s

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [110]:
d = np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 35. Write a NumPy program to change the dimension of an array.

In [111]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [112]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [113]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 36. Write a NumPy program to create a contiguous flattened array.

In [116]:
x = np.array([[10,20,30],[20,40,50]])
x

array([[10, 20, 30],
       [20, 40, 50]])

In [117]:
s = x.reshape(1,6)
s

array([[10, 20, 30, 20, 40, 50]])

### 37. Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.

In [118]:
x

array([[10, 20, 30],
       [20, 40, 50]])

In [120]:
x.shape

(2, 3)

In [121]:
type(x)

numpy.ndarray

In [122]:
x.dtype

dtype('int32')

###  38. Write a NumPy program to create a new shape to an array without changing its data.

In [123]:
y = np.array([[1,2],[3,4],[5,6]])
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [124]:
y.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

###  39. Write a NumPy program to change the data type of an array.

In [126]:
y.astype(float)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### 40. Write a NumPy program to create a new array of 3*5, filled with 2.

In [127]:
z = np.full((3,5),2)

In [128]:
z

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [130]:
# using ones
s = np.ones((3,5))*2
s

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

###  41. Write a NumPy program to create an array of 10's with the same shape and type of a given array. 

In [131]:
s = np.repeat(10,4)
s

array([10, 10, 10, 10])

### 42. Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere. 

In [132]:
s =np.identity(3)
s

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [133]:
s = np.diagflat([2,4,6,8])
s

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

### 44. Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50. 

In [134]:
a = np.arange(0,50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [135]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 45. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive. 

In [136]:
a = np.linspace(2.5,6.5,30)
a

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

### 46. Write a NumPy program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.

In [137]:
a = np.logspace(2,5,20)
a

array([   100.        ,    143.84498883,    206.91380811,    297.63514416,
          428.13323987,    615.84821107,    885.86679041,   1274.2749857 ,
         1832.98071083,   2636.65089873,   3792.69019073,   5455.59478117,
         7847.59970351,  11288.37891685,  16237.76739189,  23357.2146909 ,
        33598.18286284,  48329.30238572,  69519.27961776, 100000.        ])

In [138]:
a = np.logspace(2,5,20,endpoint=False)
a

array([  100.        ,   141.25375446,   199.5262315 ,   281.83829313,
         398.10717055,   562.34132519,   794.32823472,  1122.0184543 ,
        1584.89319246,  2238.72113857,  3162.27766017,  4466.83592151,
        6309.5734448 ,  8912.50938134, 12589.25411794, 17782.79410039,
       25118.8643151 , 35481.33892336, 50118.72336273, 70794.57843841])

### 47. Write a NumPy program to create an array which looks like below array.

In [139]:
a =np.tri(4,3)
a

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [140]:
a = np.tri(4,3,-1)
a

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

### 49. Write a NumPy program to collapse a 3-D array into one dimension array.

In [141]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
a.reshape(1,9)

array([[1., 0., 0., 0., 1., 0., 0., 0., 1.]])

In [148]:
b= np.ravel(a)
b

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

### 50. Write a NumPy program to find the 4th element of a specified array.

In [149]:
a = np.arange(2,14,2).reshape(2,3)
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [151]:
a[1,0]

8

### 51. Write a NumPy program to interchange two axes of an array. 

In [152]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [153]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

### 52. Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order. 

### 58. Write a NumPy program to concatenate two 2-dimensional arrays

In [156]:
a = np.arange(0,5)
b = np.arange(5,10)

In [157]:
display(a,b)

array([0, 1, 2, 3, 4])

array([5, 6, 7, 8, 9])

In [159]:
c = np.concatenate((a,b))

In [160]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])

In [164]:
display(a,b)

array([[0, 1, 3],
       [5, 7, 9]])

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [165]:
c= np.concatenate((a,b))

In [166]:
c

array([[ 0,  1,  3],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [168]:
d = np.concatenate((a,b),1)
d

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

### 59. Write a NumPy program to convert 1-D arrays as columns into a 2-D array. 

In [169]:
a = np.array((10,20,30))
b = np.array((40,50,60))
display(a,b)

array([10, 20, 30])

array([40, 50, 60])

In [171]:
c = np.column_stack((a,b))
c

array([[10, 40],
       [20, 50],
       [30, 60]])

### 60. Write a NumPy program to convert (in sequence depth wise (along third axis)) two 1-D arrays into a 2-D array.

In [172]:
d = np.dstack((a,b))
d

array([[[10, 40],
        [20, 50],
        [30, 60]]])

### 61. Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.

In [173]:
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [174]:
np.split(x,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]

In [175]:
np.split(x,[3,6])

[array([1, 2, 3]), array([4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]

In [176]:
np.split(x,[4,10])

[array([1, 2, 3, 4]), array([ 5,  6,  7,  8,  9, 10]), array([11, 12, 13, 14])]

### 62. Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis. 

In [179]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [181]:
np.hsplit(x,[2,6])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([], shape=(4, 0), dtype=int32)]

### 63. Write a NumPy program to get the number of nonzero elements in an array.

In [182]:
x= np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [183]:
x > 0

array([[False,  True,  True],
       [ True,  True,  True]])

In [187]:
x[x>0]

array([1, 2, 3, 4, 5])

In [188]:
np.count_nonzero(x)

5

### 64. Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.

In [189]:
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [190]:
x += np.arange(5)

In [191]:
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### 65. Write a NumPy program to test whether specified values are present in an array. 

In [192]:
x = np.array([10,15,20,25,30,26,39,50])
x

array([10, 15, 20, 25, 30, 26, 39, 50])

In [193]:
50 in x

True

In [194]:
21 in x

False

### 66. Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded. 

In [201]:
x = np.linspace(0,1,12)[1:-1]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### 68. Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100.

In [205]:
x = np.arange(1,100)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [206]:
num = x[(x % 3 == 0)|(x % 5 == 0)]

In [207]:
num

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36,
       39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72,
       75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99])

### 69. Write a NumPy program to create an array with 10^3 elements. 

In [208]:
x =np.arange(1e3)
x

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

### 70. Write a NumPy program to create display every element of a NumPy array.

In [209]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [211]:
a = []
for i in x:
    a.append(i)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


### 72. Write a NumPy program to create a 5x5x5 cube of 1's.

In [215]:
x = np.ones((5,5,5),dtype = int)
x

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [218]:
### 73. Write a NumPy program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

In [216]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [217]:
x *3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])