# Numpy Sorting Exercise

import numpy as np

In [1]:
import numpy as np

### 1. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [9]:
a = np.array([[10,40],[30,20]])
a

array([[10, 40],
       [30, 20]])

In [10]:
print('Sort the array along first axis')
np.sort(a,axis=0)

Sort the array along first axis


array([[10, 20],
       [30, 40]])

In [11]:
print('Sort the array along last axis')
np.sort(a,axis=1)

Sort the array along last axis


array([[10, 40],
       [20, 30]])

In [12]:
print('Falttened array')
np.sort(a,axis=None)

Falttened array


array([10, 20, 30, 40])

### 2. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [13]:
data_type = [('name','S15'),('class',int),('height',float)]
student_details = [('James',5,48.5),('Nail',6,52.5),('Paul',5,42.10),('Pit',5,40.11)]

In [14]:
students = np.array(student_details,dtype=data_type)
students

array([(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ),
       (b'Pit', 5, 40.11)],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

In [15]:
print('Sort by heights')
np.sort(students,order='height')

Sort by heights


array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

### 3. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal

In [16]:
# take above problem
print('Sort by using class and height')
np.sort(students,order=['class','height'])

Sort by using class and height


array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

### 4. Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

In [17]:
student_id = np.array([1023,5205,6230,1671,1682,5487])
student_height = np.array([40,42,56,58,52,49])

In [19]:
a= np.lexsort((student_id,student_height))
a

array([0, 1, 5, 4, 2, 3], dtype=int64)

In [21]:
print('Sorted data')
for i in a:
    print(student_id[i],student_height[i])

Sorted data
1023 40
5205 42
5487 49
1682 52
6230 56
1671 58


### 5. Write a NumPy program to get the indices of the sorted elements of a given array. 

In [22]:
student_id

array([1023, 5205, 6230, 1671, 1682, 5487])

In [23]:
student_id.sort()

In [24]:
student_id

array([1023, 1671, 1682, 5205, 5487, 6230])

In [26]:
# to get index
student_id

array([1023, 1671, 1682, 5205, 5487, 6230])

In [28]:
student_height

array([40, 42, 56, 58, 52, 49])

In [29]:
i = np.argsort(student_height)
i

array([0, 1, 5, 4, 2, 3], dtype=int64)

In [30]:
i = np.argsort(student_id)

In [31]:
i

array([0, 1, 2, 3, 4, 5], dtype=int64)

### 6. Write a NumPy program to sort a given complex array using the real part first, then the imaginary part. 

In [32]:
num = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]
num

[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

In [33]:
print('\nSort the complex number by using real part first')
np.sort_complex(num)


Sort the complex number by using real part first


array([1.+2.j, 3.-2.j, 3.-1.j, 3.+5.j, 4.-3.j])

### 7. Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice)

In [34]:
nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])

In [35]:
nums

array([ 70,  50,  20,  30, -11,  60,  50,  40])

In [37]:
print('Partition on 5th position')
np.partition(nums,5)

Partition on 5th position


array([-11,  30,  20,  40,  50,  50,  60,  70])

In [38]:
print('Partition on 4th position')
np.partition(nums,4)

Partition on 4th position


array([-11,  30,  20,  40,  50,  50,  60,  70])

### 8. Write a NumPy program to sort the specified number of elements from beginning of a given array.

In [39]:
a = np.random.random(10)

In [40]:
a

array([0.36429521, 0.71288399, 0.22045006, 0.61947022, 0.73678155,
       0.50748866, 0.1183267 , 0.11459634, 0.90771115, 0.94778194])

In [41]:
print('Sort first 5 element')
a[np.argpartition(a,range(5))]

Sort first 5 element


array([0.11459634, 0.1183267 , 0.22045006, 0.36429521, 0.50748866,
       0.73678155, 0.71288399, 0.61947022, 0.90771115, 0.94778194])

### 9. Write a NumPy program to sort an given array by the nth column.

In [42]:
a = np.random.randint(0,10,(3,3))
a

array([[4, 4, 8],
       [4, 7, 9],
       [3, 0, 7]])

In [43]:
print('Sort the array in the nth column')
a[a[:,1].argsort()]

Sort the array in the nth column


array([[3, 0, 7],
       [4, 4, 8],
       [4, 7, 9]])