In [1]:
import numpy as np

### 1. Write a NumPy program to generate five random numbers from the normal distribution. 

In [2]:
np.random.normal(size=5)

array([ 0.60750057,  2.37476105,  0.30117152, -0.76736944,  0.19158171])

### 2. Write a NumPy program to generate six random integers between 10 and 30.

In [4]:
np.random.randint(low=10, high=30,size=5)

array([12, 23, 12, 12, 11])

### 3. Write a NumPy program to create a 3x3x3 array with random values. 

In [5]:
np.random.random((3,3,3))

array([[[0.50960295, 0.03106232, 0.50105492],
        [0.4077624 , 0.18928864, 0.39395168],
        [0.52428469, 0.4491364 , 0.65954647]],

       [[0.96297227, 0.72655459, 0.8712161 ],
        [0.28583725, 0.01742049, 0.53908436],
        [0.27611468, 0.55738241, 0.80435388]],

       [[0.31813432, 0.85832029, 0.73679496],
        [0.91657358, 0.83773311, 0.26293926],
        [0.42416722, 0.00931346, 0.04032197]]])

In [6]:
np.random.random((4,4,4))

array([[[0.36507761, 0.49286733, 0.20001021, 0.31626495],
        [0.90834979, 0.77581974, 0.3196439 , 0.44113949],
        [0.25452276, 0.2065319 , 0.79737924, 0.63287246],
        [0.66381736, 0.33868589, 0.43098753, 0.62755439]],

       [[0.83397206, 0.57736817, 0.22550755, 0.07059679],
        [0.38610676, 0.05703019, 0.80562592, 0.25313369],
        [0.74667158, 0.51731832, 0.59557987, 0.33244219],
        [0.70243436, 0.62772884, 0.97796764, 0.09509374]],

       [[0.69900398, 0.90349616, 0.72506702, 0.10809653],
        [0.5839832 , 0.09834721, 0.66753126, 0.9184125 ],
        [0.10853352, 0.43307882, 0.32683335, 0.00284337],
        [0.38116974, 0.42336376, 0.77753717, 0.46226772]],

       [[0.31486335, 0.92774905, 0.62158446, 0.70609202],
        [0.44526866, 0.7203696 , 0.62650248, 0.00885702],
        [0.21898695, 0.36705941, 0.17017468, 0.06275954],
        [0.07263086, 0.90116183, 0.69445462, 0.5149881 ]]])

### 4. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [7]:
a = np.random.random((5,5))
a

array([[0.30962536, 0.45255868, 0.46731968, 0.02723576, 0.79688861],
       [0.77739935, 0.94672475, 0.01148864, 0.30829996, 0.89205938],
       [0.88356254, 0.40812064, 0.43851251, 0.45403106, 0.047205  ],
       [0.97321631, 0.92419583, 0.17927018, 0.19694285, 0.23824307],
       [0.2272615 , 0.18452469, 0.44516066, 0.62158284, 0.14340462]])

In [9]:
a.min()

0.011488638738262114

In [10]:
a.max()

0.973216308857757

### 5. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [11]:
a = np.random.random((10,4))

In [12]:
a

array([[0.06072284, 0.19088761, 0.69030222, 0.69975072],
       [0.60679133, 0.28427097, 0.31993079, 0.0205413 ],
       [0.64473005, 0.97859664, 0.00643175, 0.01630362],
       [0.14688667, 0.12663727, 0.78642636, 0.07793446],
       [0.80278445, 0.59157064, 0.151931  , 0.65042375],
       [0.34840202, 0.83154054, 0.22987062, 0.49135919],
       [0.6666413 , 0.04584332, 0.89262185, 0.25199566],
       [0.87880293, 0.17211357, 0.51423662, 0.51056975],
       [0.2550095 , 0.04824198, 0.06271893, 0.8605399 ],
       [0.65833458, 0.49809153, 0.68899368, 0.77519548]])

In [15]:
b = a[:5]

In [16]:
# First 5 rows of above array
b

array([[0.06072284, 0.19088761, 0.69030222, 0.69975072],
       [0.60679133, 0.28427097, 0.31993079, 0.0205413 ],
       [0.64473005, 0.97859664, 0.00643175, 0.01630362],
       [0.14688667, 0.12663727, 0.78642636, 0.07793446],
       [0.80278445, 0.59157064, 0.151931  , 0.65042375]])

### 6. Write a NumPy program to shuffle numbers between 0 and 10 (inclusive)

In [17]:
a= np.arange(10)
print('The number before shuffle :',a)

The number before shuffle : [0 1 2 3 4 5 6 7 8 9]


In [20]:
np.random.shuffle(a)

In [21]:
a

array([4, 0, 5, 7, 1, 2, 6, 3, 8, 9])

In [22]:
print('The same result using permutation')
np.random.permutation(a)

The same result using permutation


array([5, 8, 9, 3, 2, 7, 1, 0, 4, 6])

### 7. Write a NumPy program to normalize a 3x3 random matrix.

In [25]:
a = np.random.random((3,3))
a

array([[0.03602391, 0.05868977, 0.13977286],
       [0.08390881, 0.19354547, 0.21722503],
       [0.89853838, 0.22137115, 0.28019275]])

In [26]:
# Now narmalize the matrix
# first findout max and min value from matrix
a_max,a_min = a.max(),a.min()

In [28]:
a = (a - a_min)/(a_max - a_min)

In [29]:
print('After normalization')
a

After normalization


array([[0.        , 0.02627881, 0.12028661],
       [0.05551779, 0.18263062, 0.21008473],
       [1.        , 0.21489175, 0.28308955]])

### 8. Write a NumPy program to create a random vector of size 10 and sort it.

In [31]:
a = np.random.random((10))
a

array([0.17015377, 0.2930003 , 0.04371914, 0.69614747, 0.3415107 ,
       0.13368881, 0.43475206, 0.34012438, 0.90456437, 0.94360675])

In [32]:
a.sort()

In [34]:
print('vector after sorting')
a

vector after sorting


array([0.04371914, 0.13368881, 0.17015377, 0.2930003 , 0.34012438,
       0.3415107 , 0.43475206, 0.69614747, 0.90456437, 0.94360675])

### 9. Write a NumPy program to find the nearest value from a given value in an array.

In [35]:
x = np.random.uniform(low=1,high=10,size=5)

In [36]:
near = 4

In [37]:
print('Nearest value is')
nearset_value = x.flat[np.abs(x - near).argmin()]
nearset_value

Nearest value is


4.32127277685964

### 10. Write a NumPy program to check two random arrays are equal or not. 

In [38]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
display(a,b)

array([1, 1, 0, 1, 0])

array([1, 1, 0, 0, 0])

In [39]:
array_equal = np.allclose(a,b)
array_equal

False

### 11. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1. 

In [40]:
a = np.random.random(size=15)
a

array([0.26058289, 0.40028603, 0.43639503, 0.56482847, 0.02003894,
       0.03622398, 0.15569047, 0.72218002, 0.09483762, 0.12405556,
       0.23986269, 0.41970816, 0.7294658 , 0.40830145, 0.21898411])

In [42]:
# now replace max value by -1
a[a.argmax()] = -1

In [43]:
print('maximum value is replaced by -1')
a

maximum value is replaced by -1


array([ 0.26058289,  0.40028603,  0.43639503,  0.56482847,  0.02003894,
        0.03622398,  0.15569047,  0.72218002,  0.09483762,  0.12405556,
        0.23986269,  0.41970816, -1.        ,  0.40830145,  0.21898411])

### 12. Write a NumPy program to find point by point distances of a random vector with shape (10,2) representing coordinates. 

### 13. Write a NumPy program to find the most frequent value in an array.

In [44]:
a = np.random.randint(1,5,10)
a

array([2, 3, 4, 1, 3, 1, 1, 3, 1, 1])

In [45]:
# now find the most repeted number from above array
print('Most frequent number is')
np.bincount(a).argmax()

Most frequent number is


1

### 14. Write a NumPy program to convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates

In [46]:
a = np.random.random((10,2))
a

array([[0.99036219, 0.07985469],
       [0.76496375, 0.47218225],
       [0.09892821, 0.06383781],
       [0.73672563, 0.20669367],
       [0.15900558, 0.65057599],
       [0.64216386, 0.17573886],
       [0.75081712, 0.04230861],
       [0.27326937, 0.05829098],
       [0.73460604, 0.04005692],
       [0.33598368, 0.92396448]])

### 15. Write a NumPy program to find the closest value (to a given scalar) in an array.

In [47]:
a = np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
b = float(input('Enter the value in between in a : '))
nearset_value = a.flat[np.abs(a - b).argmin()]
print('Nearest value is ',nearset_value)

Enter the value in between in a : 35.8
Nearest value is  36


### 16. Write a NumPy program to get the n largest values of an array. 

In [50]:
a = np.random.randint(1,15,5)
a

array([ 6, 14, 10,  9,  5])

In [52]:
a.max()

14

In [53]:
a.sort()

In [54]:
a

array([ 5,  6,  9, 10, 14])

In [55]:
a[-1]

14

### 17. Write a NumPy program to create a three-dimension array with shape (300,400,5) and set to a variable. Fill the array elements with values using unsigned integer (0 to 255).

In [56]:
a = np.random.randint(low=0,high=256,size=(300,400,5))
a

array([[[175, 181, 128, 206, 151],
        [226,  38,  30,  63, 105],
        [166,  67,  14,   4,  69],
        ...,
        [ 25, 157,  91, 157,  17],
        [ 15,  56,  24, 108,  82],
        [ 27, 124,  89, 157,  47]],

       [[158, 185,  74, 151,  85],
        [191, 195, 150,  12, 136],
        [166, 195, 233,  66, 158],
        ...,
        [149, 199, 109,  57,  16],
        [  1, 153, 140,  39,  25],
        [  7, 225,  49, 172, 230]],

       [[ 62, 158,  37, 212, 137],
        [ 41, 149,  62, 123,  93],
        [217, 255, 189, 212, 110],
        ...,
        [ 52, 165, 208, 228,  90],
        [ 83,  90, 102,  34, 227],
        [232, 206, 201, 152, 101]],

       ...,

       [[233, 114, 252, 163, 138],
        [ 52, 154, 157,  59, 146],
        [183,  64, 134, 117, 227],
        ...,
        [200,  27, 223, 164,  88],
        [174, 175, 116, 145, 206],
        [145,   1, 189,  29,  20]],

       [[ 14, 170,  43, 215,  87],
        [ 80, 133,  77, 113,  70],
        [217, 230